export type ElementData = {
    symbol: string;
    name: string;
    atomicNumber: number;
    atomicWeight: number;
    period: number;
    group: number | null;
    category: string;
    electronConfiguration: string;
    valenceElectrons: number | null;
    commonOxidationStates: number[];
    electronegativity: number | null;
    atomicRadiusPm: number | null;
    ionizationEnergy1kJMol: number | null;
    electronAffinitykJMol: number | null;
    phaseAtSTP: "solid" | "liquid" | "gas" | "unknown";
    meltingPointK: number | null;
    boilingPointK: number | null;
    densityGcm3: number | null;
};

// Sources used to populate this static table:
// - PubChem Periodic Table CSV for oxidation states, radius, standard state, and basic descriptors
// - Bowserinator Periodic-Table-JSON for shells, semantic electron configuration, electron affinity, and first ionization energy in kJ/mol
export const PeriodicTable: Record<string, ElementData> = {
    H: {
        symbol: 'H',
        name: "Hydrogen",
        atomicNumber: 1,
        atomicWeight: 1.008,
        period: 1,
        group: 1,
        category: "nonmetal",
        electronConfiguration: "1s1",
        valenceElectrons: 1,
        commonOxidationStates: [1, -1],
        electronegativity: 2.2,
        atomicRadiusPm: 120,
        ionizationEnergy1kJMol: 1312,
        electronAffinitykJMol: 72.769,
        phaseAtSTP: 'gas',
        meltingPointK: 13.81,
        boilingPointK: 20.28,
        densityGcm3: 0.00008988,
    },
    He: {
        symbol: 'He',
        name: "Helium",
        atomicNumber: 2,
        atomicWeight: 4.0026022,
        period: 1,
        group: 18,
        category: "noble gas",
        electronConfiguration: "1s2",
        valenceElectrons: 2,
        commonOxidationStates: [0],
        electronegativity: null,
        atomicRadiusPm: 140,
        ionizationEnergy1kJMol: 2372.3,
        electronAffinitykJMol: -48,
        phaseAtSTP: 'gas',
        meltingPointK: 0.95,
        boilingPointK: 4.22,
        densityGcm3: 0.0001785,
    },
    Li: {
        symbol: 'Li',
        name: "Lithium",
        atomicNumber: 3,
        atomicWeight: 6.94,
        period: 2,
        group: 1,
        category: "alkali metal",
        electronConfiguration: "[He] 2s1",
        valenceElectrons: 1,
        commonOxidationStates: [1],
        electronegativity: 0.98,
        atomicRadiusPm: 182,
        ionizationEnergy1kJMol: 520.2,
        electronAffinitykJMol: 59.6326,
        phaseAtSTP: 'solid',
        meltingPointK: 453.65,
        boilingPointK: 1615,
        densityGcm3: 0.534,
    },
    Be: {
        symbol: 'Be',
        name: "Beryllium",
        atomicNumber: 4,
        atomicWeight: 9.01218315,
        period: 2,
        group: 2,
        category: "alkaline earth metal",
        electronConfiguration: "[He] 2s2",
        valenceElectrons: 2,
        commonOxidationStates: [2],
        electronegativity: 1.57,
        atomicRadiusPm: 153,
        ionizationEnergy1kJMol: 899.5,
        electronAffinitykJMol: -48,
        phaseAtSTP: 'solid',
        meltingPointK: 1560,
        boilingPointK: 2744,
        densityGcm3: 1.85,
    },
    B: {
        symbol: 'B',
        name: "Boron",
        atomicNumber: 5,
        atomicWeight: 10.81,
        period: 2,
        group: 13,
        category: "metalloid",
        electronConfiguration: "[He] 2s2 2p1",
        valenceElectrons: 3,
        commonOxidationStates: [3],
        electronegativity: 2.04,
        atomicRadiusPm: 192,
        ionizationEnergy1kJMol: 800.6,
        electronAffinitykJMol: 26.989,
        phaseAtSTP: 'solid',
        meltingPointK: 2348,
        boilingPointK: 4273,
        densityGcm3: 2.37,
    },
    C: {
        symbol: 'C',
        name: "Carbon",
        atomicNumber: 6,
        atomicWeight: 12.011,
        period: 2,
        group: 14,
        category: "nonmetal",
        electronConfiguration: "[He] 2s2 2p2",
        valenceElectrons: 4,
        commonOxidationStates: [4, 2, -4],
        electronegativity: 2.55,
        atomicRadiusPm: 170,
        ionizationEnergy1kJMol: 1086.5,
        electronAffinitykJMol: 121.7763,
        phaseAtSTP: 'solid',
        meltingPointK: 3823,
        boilingPointK: 4098,
        densityGcm3: 2.267,
    },
    N: {
        symbol: 'N',
        name: "Nitrogen",
        atomicNumber: 7,
        atomicWeight: 14.007,
        period: 2,
        group: 15,
        category: "nonmetal",
        electronConfiguration: "[He] 2s2 2p3",
        valenceElectrons: 5,
        commonOxidationStates: [5, 4, 3, 2, 1, -1, -2, -3],
        electronegativity: 3.04,
        atomicRadiusPm: 155,
        ionizationEnergy1kJMol: 1402.3,
        electronAffinitykJMol: -6.8,
        phaseAtSTP: 'gas',
        meltingPointK: 63.15,
        boilingPointK: 77.36,
        densityGcm3: 0.0012506,
    },
    O: {
        symbol: 'O',
        name: "Oxygen",
        atomicNumber: 8,
        atomicWeight: 15.999,
        period: 2,
        group: 16,
        category: "nonmetal",
        electronConfiguration: "[He] 2s2 2p4",
        valenceElectrons: 6,
        commonOxidationStates: [-2],
        electronegativity: 3.44,
        atomicRadiusPm: 152,
        ionizationEnergy1kJMol: 1313.9,
        electronAffinitykJMol: 140.976,
        phaseAtSTP: 'gas',
        meltingPointK: 54.36,
        boilingPointK: 90.2,
        densityGcm3: 0.001429,
    },
    F: {
        symbol: 'F',
        name: "Fluorine",
        atomicNumber: 9,
        atomicWeight: 18.9984031636,
        period: 2,
        group: 17,
        category: "halogen",
        electronConfiguration: "[He] 2s2 2p5",
        valenceElectrons: 7,
        commonOxidationStates: [-1],
        electronegativity: 3.98,
        atomicRadiusPm: 135,
        ionizationEnergy1kJMol: 1681,
        electronAffinitykJMol: 328.1649,
        phaseAtSTP: 'gas',
        meltingPointK: 53.53,
        boilingPointK: 85.03,
        densityGcm3: 0.001696,
    },
    Ne: {
        symbol: 'Ne',
        name: "Neon",
        atomicNumber: 10,
        atomicWeight: 20.17976,
        period: 2,
        group: 18,
        category: "noble gas",
        electronConfiguration: "[He] 2s2 2p6",
        valenceElectrons: 8,
        commonOxidationStates: [0],
        electronegativity: null,
        atomicRadiusPm: 154,
        ionizationEnergy1kJMol: 2080.7,
        electronAffinitykJMol: -116,
        phaseAtSTP: 'gas',
        meltingPointK: 24.56,
        boilingPointK: 27.07,
        densityGcm3: 0.0008999,
    },
    Na: {
        symbol: 'Na',
        name: "Sodium",
        atomicNumber: 11,
        atomicWeight: 22.989769282,
        period: 3,
        group: 1,
        category: "alkali metal",
        electronConfiguration: "[Ne] 3s1",
        valenceElectrons: 1,
        commonOxidationStates: [1],
        electronegativity: 0.93,
        atomicRadiusPm: 227,
        ionizationEnergy1kJMol: 495.8,
        electronAffinitykJMol: 52.867,
        phaseAtSTP: 'solid',
        meltingPointK: 370.95,
        boilingPointK: 1156,
        densityGcm3: 0.97,
    },
    Mg: {
        symbol: 'Mg',
        name: "Magnesium",
        atomicNumber: 12,
        atomicWeight: 24.305,
        period: 3,
        group: 2,
        category: "alkaline earth metal",
        electronConfiguration: "[Ne] 3s2",
        valenceElectrons: 2,
        commonOxidationStates: [2],
        electronegativity: 1.31,
        atomicRadiusPm: 173,
        ionizationEnergy1kJMol: 737.7,
        electronAffinitykJMol: -40,
        phaseAtSTP: 'solid',
        meltingPointK: 923,
        boilingPointK: 1363,
        densityGcm3: 1.74,
    },
    Al: {
        symbol: 'Al',
        name: "Aluminum",
        atomicNumber: 13,
        atomicWeight: 26.98153857,
        period: 3,
        group: 13,
        category: "post-transition metal",
        electronConfiguration: "[Ne] 3s2 3p1",
        valenceElectrons: 3,
        commonOxidationStates: [3],
        electronegativity: 1.61,
        atomicRadiusPm: 184,
        ionizationEnergy1kJMol: 577.5,
        electronAffinitykJMol: 41.762,
        phaseAtSTP: 'solid',
        meltingPointK: 933.437,
        boilingPointK: 2792,
        densityGcm3: 2.7,
    },
    Si: {
        symbol: 'Si',
        name: "Silicon",
        atomicNumber: 14,
        atomicWeight: 28.085,
        period: 3,
        group: 14,
        category: "metalloid",
        electronConfiguration: "[Ne] 3s2 3p2",
        valenceElectrons: 4,
        commonOxidationStates: [4, 2, -4],
        electronegativity: 1.9,
        atomicRadiusPm: 210,
        ionizationEnergy1kJMol: 786.5,
        electronAffinitykJMol: 134.0684,
        phaseAtSTP: 'solid',
        meltingPointK: 1687,
        boilingPointK: 3538,
        densityGcm3: 2.3296,
    },
    P: {
        symbol: 'P',
        name: "Phosphorus",
        atomicNumber: 15,
        atomicWeight: 30.9737619985,
        period: 3,
        group: 15,
        category: "nonmetal",
        electronConfiguration: "[Ne] 3s2 3p3",
        valenceElectrons: 5,
        commonOxidationStates: [5, 3, -3],
        electronegativity: 2.19,
        atomicRadiusPm: 180,
        ionizationEnergy1kJMol: 1011.8,
        electronAffinitykJMol: 72.037,
        phaseAtSTP: 'solid',
        meltingPointK: 317.3,
        boilingPointK: 553.65,
        densityGcm3: 1.82,
    },
    S: {
        symbol: 'S',
        name: "Sulfur",
        atomicNumber: 16,
        atomicWeight: 32.06,
        period: 3,
        group: 16,
        category: "nonmetal",
        electronConfiguration: "[Ne] 3s2 3p4",
        valenceElectrons: 6,
        commonOxidationStates: [6, 4, -2],
        electronegativity: 2.58,
        atomicRadiusPm: 180,
        ionizationEnergy1kJMol: 999.6,
        electronAffinitykJMol: 200.4101,
        phaseAtSTP: 'solid',
        meltingPointK: 388.36,
        boilingPointK: 717.75,
        densityGcm3: 2.067,
    },
    Cl: {
        symbol: 'Cl',
        name: "Chlorine",
        atomicNumber: 17,
        atomicWeight: 35.45,
        period: 3,
        group: 17,
        category: "halogen",
        electronConfiguration: "[Ne] 3s2 3p5",
        valenceElectrons: 7,
        commonOxidationStates: [7, 5, 1, -1],
        electronegativity: 3.16,
        atomicRadiusPm: 175,
        ionizationEnergy1kJMol: 1251.2,
        electronAffinitykJMol: 348.575,
        phaseAtSTP: 'gas',
        meltingPointK: 171.65,
        boilingPointK: 239.11,
        densityGcm3: 0.003214,
    },
    Ar: {
        symbol: 'Ar',
        name: "Argon",
        atomicNumber: 18,
        atomicWeight: 39.9481,
        period: 3,
        group: 18,
        category: "noble gas",
        electronConfiguration: "[Ne] 3s2 3p6",
        valenceElectrons: 8,
        commonOxidationStates: [0],
        electronegativity: null,
        atomicRadiusPm: 188,
        ionizationEnergy1kJMol: 1520.6,
        electronAffinitykJMol: -96,
        phaseAtSTP: 'gas',
        meltingPointK: 83.8,
        boilingPointK: 87.3,
        densityGcm3: 0.0017837,
    },
    K: {
        symbol: 'K',
        name: "Potassium",
        atomicNumber: 19,
        atomicWeight: 39.09831,
        period: 4,
        group: 1,
        category: "alkali metal",
        electronConfiguration: "[Ar] 4s1",
        valenceElectrons: 1,
        commonOxidationStates: [1],
        electronegativity: 0.82,
        atomicRadiusPm: 275,
        ionizationEnergy1kJMol: 418.8,
        electronAffinitykJMol: 48.383,
        phaseAtSTP: 'solid',
        meltingPointK: 336.53,
        boilingPointK: 1032,
        densityGcm3: 0.89,
    },
    Ca: {
        symbol: 'Ca',
        name: "Calcium",
        atomicNumber: 20,
        atomicWeight: 40.0784,
        period: 4,
        group: 2,
        category: "alkaline earth metal",
        electronConfiguration: "[Ar] 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [2],
        electronegativity: 1,
        atomicRadiusPm: 231,
        ionizationEnergy1kJMol: 589.8,
        electronAffinitykJMol: 2.37,
        phaseAtSTP: 'solid',
        meltingPointK: 1115,
        boilingPointK: 1757,
        densityGcm3: 1.54,
    },
    Sc: {
        symbol: 'Sc',
        name: "Scandium",
        atomicNumber: 21,
        atomicWeight: 44.9559085,
        period: 4,
        group: 3,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d1 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.36,
        atomicRadiusPm: 211,
        ionizationEnergy1kJMol: 633.1,
        electronAffinitykJMol: 18,
        phaseAtSTP: 'solid',
        meltingPointK: 1814,
        boilingPointK: 3109,
        densityGcm3: 2.99,
    },
    Ti: {
        symbol: 'Ti',
        name: "Titanium",
        atomicNumber: 22,
        atomicWeight: 47.8671,
        period: 4,
        group: 4,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d2 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [4, 3, 2],
        electronegativity: 1.54,
        atomicRadiusPm: 187,
        ionizationEnergy1kJMol: 658.8,
        electronAffinitykJMol: 7.289,
        phaseAtSTP: 'solid',
        meltingPointK: 1941,
        boilingPointK: 3560,
        densityGcm3: 4.5,
    },
    V: {
        symbol: 'V',
        name: "Vanadium",
        atomicNumber: 23,
        atomicWeight: 50.94151,
        period: 4,
        group: 5,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d3 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [5, 4, 3, 2],
        electronegativity: 1.63,
        atomicRadiusPm: 179,
        ionizationEnergy1kJMol: 650.9,
        electronAffinitykJMol: 50.911,
        phaseAtSTP: 'solid',
        meltingPointK: 2183,
        boilingPointK: 3680,
        densityGcm3: 6,
    },
    Cr: {
        symbol: 'Cr',
        name: "Chromium",
        atomicNumber: 24,
        atomicWeight: 51.99616,
        period: 4,
        group: 6,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d5 4s1",
        valenceElectrons: 1,
        commonOxidationStates: [6, 3, 2],
        electronegativity: 1.66,
        atomicRadiusPm: 189,
        ionizationEnergy1kJMol: 652.9,
        electronAffinitykJMol: 65.21,
        phaseAtSTP: 'solid',
        meltingPointK: 2180,
        boilingPointK: 2944,
        densityGcm3: 7.15,
    },
    Mn: {
        symbol: 'Mn',
        name: "Manganese",
        atomicNumber: 25,
        atomicWeight: 54.9380443,
        period: 4,
        group: 7,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d5 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [7, 4, 3, 2],
        electronegativity: 1.55,
        atomicRadiusPm: 197,
        ionizationEnergy1kJMol: 717.3,
        electronAffinitykJMol: -50,
        phaseAtSTP: 'solid',
        meltingPointK: 1519,
        boilingPointK: 2334,
        densityGcm3: 7.3,
    },
    Fe: {
        symbol: 'Fe',
        name: "Iron",
        atomicNumber: 26,
        atomicWeight: 55.8452,
        period: 4,
        group: 8,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d6 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [3, 2],
        electronegativity: 1.83,
        atomicRadiusPm: 194,
        ionizationEnergy1kJMol: 762.5,
        electronAffinitykJMol: 14.785,
        phaseAtSTP: 'solid',
        meltingPointK: 1811,
        boilingPointK: 3134,
        densityGcm3: 7.874,
    },
    Co: {
        symbol: 'Co',
        name: "Cobalt",
        atomicNumber: 27,
        atomicWeight: 58.9331944,
        period: 4,
        group: 9,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d7 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [3, 2],
        electronegativity: 1.88,
        atomicRadiusPm: 192,
        ionizationEnergy1kJMol: 760.4,
        electronAffinitykJMol: 63.898,
        phaseAtSTP: 'solid',
        meltingPointK: 1768,
        boilingPointK: 3200,
        densityGcm3: 8.86,
    },
    Ni: {
        symbol: 'Ni',
        name: "Nickel",
        atomicNumber: 28,
        atomicWeight: 58.69344,
        period: 4,
        group: 10,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d8 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [3, 2],
        electronegativity: 1.91,
        atomicRadiusPm: 163,
        ionizationEnergy1kJMol: 737.1,
        electronAffinitykJMol: 111.65,
        phaseAtSTP: 'solid',
        meltingPointK: 1728,
        boilingPointK: 3186,
        densityGcm3: 8.912,
    },
    Cu: {
        symbol: 'Cu',
        name: "Copper",
        atomicNumber: 29,
        atomicWeight: 63.5463,
        period: 4,
        group: 11,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d10 4s1",
        valenceElectrons: 1,
        commonOxidationStates: [2, 1],
        electronegativity: 1.9,
        atomicRadiusPm: 140,
        ionizationEnergy1kJMol: 745.5,
        electronAffinitykJMol: 119.235,
        phaseAtSTP: 'solid',
        meltingPointK: 1357.77,
        boilingPointK: 2835,
        densityGcm3: 8.933,
    },
    Zn: {
        symbol: 'Zn',
        name: "Zinc",
        atomicNumber: 30,
        atomicWeight: 65.382,
        period: 4,
        group: 12,
        category: "transition metal",
        electronConfiguration: "[Ar] 3d10 4s2",
        valenceElectrons: 2,
        commonOxidationStates: [2],
        electronegativity: 1.65,
        atomicRadiusPm: 139,
        ionizationEnergy1kJMol: 906.4,
        electronAffinitykJMol: -58,
        phaseAtSTP: 'solid',
        meltingPointK: 692.68,
        boilingPointK: 1180,
        densityGcm3: 7.134,
    },
    Ga: {
        symbol: 'Ga',
        name: "Gallium",
        atomicNumber: 31,
        atomicWeight: 69.7231,
        period: 4,
        group: 13,
        category: "post-transition metal",
        electronConfiguration: "[Ar] 3d10 4s2 4p1",
        valenceElectrons: 3,
        commonOxidationStates: [3],
        electronegativity: 1.81,
        atomicRadiusPm: 187,
        ionizationEnergy1kJMol: 578.8,
        electronAffinitykJMol: 41,
        phaseAtSTP: 'solid',
        meltingPointK: 302.91,
        boilingPointK: 2477,
        densityGcm3: 5.91,
    },
    Ge: {
        symbol: 'Ge',
        name: "Germanium",
        atomicNumber: 32,
        atomicWeight: 72.6308,
        period: 4,
        group: 14,
        category: "metalloid",
        electronConfiguration: "[Ar] 3d10 4s2 4p2",
        valenceElectrons: 4,
        commonOxidationStates: [4, 2],
        electronegativity: 2.01,
        atomicRadiusPm: 211,
        ionizationEnergy1kJMol: 762,
        electronAffinitykJMol: 118.9352,
        phaseAtSTP: 'solid',
        meltingPointK: 1211.4,
        boilingPointK: 3106,
        densityGcm3: 5.323,
    },
    As: {
        symbol: 'As',
        name: "Arsenic",
        atomicNumber: 33,
        atomicWeight: 74.9215956,
        period: 4,
        group: 15,
        category: "metalloid",
        electronConfiguration: "[Ar] 3d10 4s2 4p3",
        valenceElectrons: 5,
        commonOxidationStates: [5, 3, -3],
        electronegativity: 2.18,
        atomicRadiusPm: 185,
        ionizationEnergy1kJMol: 947,
        electronAffinitykJMol: 77.65,
        phaseAtSTP: 'solid',
        meltingPointK: 1090,
        boilingPointK: 887,
        densityGcm3: 5.776,
    },
    Se: {
        symbol: 'Se',
        name: "Selenium",
        atomicNumber: 34,
        atomicWeight: 78.9718,
        period: 4,
        group: 16,
        category: "nonmetal",
        electronConfiguration: "[Ar] 3d10 4s2 4p4",
        valenceElectrons: 6,
        commonOxidationStates: [6, 4, -2],
        electronegativity: 2.55,
        atomicRadiusPm: 190,
        ionizationEnergy1kJMol: 941,
        electronAffinitykJMol: 194.9587,
        phaseAtSTP: 'solid',
        meltingPointK: 493.65,
        boilingPointK: 958,
        densityGcm3: 4.809,
    },
    Br: {
        symbol: 'Br',
        name: "Bromine",
        atomicNumber: 35,
        atomicWeight: 79.904,
        period: 4,
        group: 17,
        category: "halogen",
        electronConfiguration: "[Ar] 3d10 4s2 4p5",
        valenceElectrons: 7,
        commonOxidationStates: [5, 1, -1],
        electronegativity: 2.96,
        atomicRadiusPm: 183,
        ionizationEnergy1kJMol: 1139.9,
        electronAffinitykJMol: 324.537,
        phaseAtSTP: 'liquid',
        meltingPointK: 265.95,
        boilingPointK: 331.95,
        densityGcm3: 3.11,
    },
    Kr: {
        symbol: 'Kr',
        name: "Krypton",
        atomicNumber: 36,
        atomicWeight: 83.7982,
        period: 4,
        group: 18,
        category: "noble gas",
        electronConfiguration: "[Ar] 3d10 4s2 4p6",
        valenceElectrons: 8,
        commonOxidationStates: [0],
        electronegativity: 3,
        atomicRadiusPm: 202,
        ionizationEnergy1kJMol: 1350.8,
        electronAffinitykJMol: -96,
        phaseAtSTP: 'gas',
        meltingPointK: 115.79,
        boilingPointK: 119.93,
        densityGcm3: 0.003733,
    },
    Rb: {
        symbol: 'Rb',
        name: "Rubidium",
        atomicNumber: 37,
        atomicWeight: 85.46783,
        period: 5,
        group: 1,
        category: "alkali metal",
        electronConfiguration: "[Kr] 5s1",
        valenceElectrons: 1,
        commonOxidationStates: [1],
        electronegativity: 0.82,
        atomicRadiusPm: 303,
        ionizationEnergy1kJMol: 403,
        electronAffinitykJMol: 46.884,
        phaseAtSTP: 'solid',
        meltingPointK: 312.46,
        boilingPointK: 961,
        densityGcm3: 1.53,
    },
    Sr: {
        symbol: 'Sr',
        name: "Strontium",
        atomicNumber: 38,
        atomicWeight: 87.621,
        period: 5,
        group: 2,
        category: "alkaline earth metal",
        electronConfiguration: "[Kr] 5s2",
        valenceElectrons: 2,
        commonOxidationStates: [2],
        electronegativity: 0.95,
        atomicRadiusPm: 249,
        ionizationEnergy1kJMol: 549.5,
        electronAffinitykJMol: 5.023,
        phaseAtSTP: 'solid',
        meltingPointK: 1050,
        boilingPointK: 1655,
        densityGcm3: 2.64,
    },
    Y: {
        symbol: 'Y',
        name: "Yttrium",
        atomicNumber: 39,
        atomicWeight: 88.905842,
        period: 5,
        group: 3,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d1 5s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.22,
        atomicRadiusPm: 219,
        ionizationEnergy1kJMol: 600,
        electronAffinitykJMol: 29.6,
        phaseAtSTP: 'solid',
        meltingPointK: 1795,
        boilingPointK: 3618,
        densityGcm3: 4.47,
    },
    Zr: {
        symbol: 'Zr',
        name: "Zirconium",
        atomicNumber: 40,
        atomicWeight: 91.2242,
        period: 5,
        group: 4,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d2 5s2",
        valenceElectrons: 2,
        commonOxidationStates: [4],
        electronegativity: 1.33,
        atomicRadiusPm: 186,
        ionizationEnergy1kJMol: 640.1,
        electronAffinitykJMol: 41.806,
        phaseAtSTP: 'solid',
        meltingPointK: 2128,
        boilingPointK: 4682,
        densityGcm3: 6.52,
    },
    Nb: {
        symbol: 'Nb',
        name: "Niobium",
        atomicNumber: 41,
        atomicWeight: 92.906372,
        period: 5,
        group: 5,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d4 5s1",
        valenceElectrons: 1,
        commonOxidationStates: [5, 3],
        electronegativity: 1.6,
        atomicRadiusPm: 207,
        ionizationEnergy1kJMol: 652.1,
        electronAffinitykJMol: 88.516,
        phaseAtSTP: 'solid',
        meltingPointK: 2750,
        boilingPointK: 5017,
        densityGcm3: 8.57,
    },
    Mo: {
        symbol: 'Mo',
        name: "Molybdenum",
        atomicNumber: 42,
        atomicWeight: 95.951,
        period: 5,
        group: 6,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d5 5s1",
        valenceElectrons: 1,
        commonOxidationStates: [6],
        electronegativity: 2.16,
        atomicRadiusPm: 209,
        ionizationEnergy1kJMol: 684.3,
        electronAffinitykJMol: 72.1,
        phaseAtSTP: 'solid',
        meltingPointK: 2896,
        boilingPointK: 4912,
        densityGcm3: 10.2,
    },
    Tc: {
        symbol: 'Tc',
        name: "Technetium",
        atomicNumber: 43,
        atomicWeight: 98,
        period: 5,
        group: 7,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d5 5s2",
        valenceElectrons: 2,
        commonOxidationStates: [7, 6, 4],
        electronegativity: 1.9,
        atomicRadiusPm: 209,
        ionizationEnergy1kJMol: 702,
        electronAffinitykJMol: 53,
        phaseAtSTP: 'solid',
        meltingPointK: 2430,
        boilingPointK: 4538,
        densityGcm3: 11,
    },
    Ru: {
        symbol: 'Ru',
        name: "Ruthenium",
        atomicNumber: 44,
        atomicWeight: 101.072,
        period: 5,
        group: 8,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d7 5s1",
        valenceElectrons: 1,
        commonOxidationStates: [3],
        electronegativity: 2.2,
        atomicRadiusPm: 207,
        ionizationEnergy1kJMol: 710.2,
        electronAffinitykJMol: 100.96,
        phaseAtSTP: 'solid',
        meltingPointK: 2607,
        boilingPointK: 4423,
        densityGcm3: 12.1,
    },
    Rh: {
        symbol: 'Rh',
        name: "Rhodium",
        atomicNumber: 45,
        atomicWeight: 102.905502,
        period: 5,
        group: 9,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d8 5s1",
        valenceElectrons: 1,
        commonOxidationStates: [3],
        electronegativity: 2.28,
        atomicRadiusPm: 195,
        ionizationEnergy1kJMol: 719.7,
        electronAffinitykJMol: 110.27,
        phaseAtSTP: 'solid',
        meltingPointK: 2237,
        boilingPointK: 3968,
        densityGcm3: 12.4,
    },
    Pd: {
        symbol: 'Pd',
        name: "Palladium",
        atomicNumber: 46,
        atomicWeight: 106.421,
        period: 5,
        group: 10,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d10",
        valenceElectrons: 18,
        commonOxidationStates: [3, 2],
        electronegativity: 2.2,
        atomicRadiusPm: 202,
        ionizationEnergy1kJMol: 804.4,
        electronAffinitykJMol: 54.24,
        phaseAtSTP: 'solid',
        meltingPointK: 1828.05,
        boilingPointK: 3236,
        densityGcm3: 12,
    },
    Ag: {
        symbol: 'Ag',
        name: "Silver",
        atomicNumber: 47,
        atomicWeight: 107.86822,
        period: 5,
        group: 11,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d10 5s1",
        valenceElectrons: 1,
        commonOxidationStates: [1],
        electronegativity: 1.93,
        atomicRadiusPm: 172,
        ionizationEnergy1kJMol: 731,
        electronAffinitykJMol: 125.862,
        phaseAtSTP: 'solid',
        meltingPointK: 1234.93,
        boilingPointK: 2435,
        densityGcm3: 10.501,
    },
    Cd: {
        symbol: 'Cd',
        name: "Cadmium",
        atomicNumber: 48,
        atomicWeight: 112.4144,
        period: 5,
        group: 12,
        category: "transition metal",
        electronConfiguration: "[Kr] 4d10 5s2",
        valenceElectrons: 2,
        commonOxidationStates: [2],
        electronegativity: 1.69,
        atomicRadiusPm: 158,
        ionizationEnergy1kJMol: 867.8,
        electronAffinitykJMol: -68,
        phaseAtSTP: 'solid',
        meltingPointK: 594.22,
        boilingPointK: 1040,
        densityGcm3: 8.69,
    },
    In: {
        symbol: 'In',
        name: "Indium",
        atomicNumber: 49,
        atomicWeight: 114.8181,
        period: 5,
        group: 13,
        category: "post-transition metal",
        electronConfiguration: "[Kr] 4d10 5s2 5p1",
        valenceElectrons: 3,
        commonOxidationStates: [3],
        electronegativity: 1.78,
        atomicRadiusPm: 193,
        ionizationEnergy1kJMol: 558.3,
        electronAffinitykJMol: 37.043,
        phaseAtSTP: 'solid',
        meltingPointK: 429.75,
        boilingPointK: 2345,
        densityGcm3: 7.31,
    },
    Sn: {
        symbol: 'Sn',
        name: "Tin",
        atomicNumber: 50,
        atomicWeight: 118.7107,
        period: 5,
        group: 14,
        category: "post-transition metal",
        electronConfiguration: "[Kr] 4d10 5s2 5p2",
        valenceElectrons: 4,
        commonOxidationStates: [4, 2],
        electronegativity: 1.96,
        atomicRadiusPm: 217,
        ionizationEnergy1kJMol: 708.6,
        electronAffinitykJMol: 107.2984,
        phaseAtSTP: 'solid',
        meltingPointK: 505.08,
        boilingPointK: 2875,
        densityGcm3: 7.287,
    },
    Sb: {
        symbol: 'Sb',
        name: "Antimony",
        atomicNumber: 51,
        atomicWeight: 121.7601,
        period: 5,
        group: 15,
        category: "metalloid",
        electronConfiguration: "[Kr] 4d10 5s2 5p3",
        valenceElectrons: 5,
        commonOxidationStates: [5, 3, -3],
        electronegativity: 2.05,
        atomicRadiusPm: 206,
        ionizationEnergy1kJMol: 834,
        electronAffinitykJMol: 101.059,
        phaseAtSTP: 'solid',
        meltingPointK: 903.78,
        boilingPointK: 1860,
        densityGcm3: 6.685,
    },
    Te: {
        symbol: 'Te',
        name: "Tellurium",
        atomicNumber: 52,
        atomicWeight: 127.603,
        period: 5,
        group: 16,
        category: "metalloid",
        electronConfiguration: "[Kr] 4d10 5s2 5p4",
        valenceElectrons: 6,
        commonOxidationStates: [6, 4, -2],
        electronegativity: 2.1,
        atomicRadiusPm: 206,
        ionizationEnergy1kJMol: 869.3,
        electronAffinitykJMol: 190.161,
        phaseAtSTP: 'solid',
        meltingPointK: 722.66,
        boilingPointK: 1261,
        densityGcm3: 6.232,
    },
    I: {
        symbol: 'I',
        name: "Iodine",
        atomicNumber: 53,
        atomicWeight: 126.904473,
        period: 5,
        group: 17,
        category: "halogen",
        electronConfiguration: "[Kr] 4d10 5s2 5p5",
        valenceElectrons: 7,
        commonOxidationStates: [7, 5, 1, -1],
        electronegativity: 2.66,
        atomicRadiusPm: 198,
        ionizationEnergy1kJMol: 1008.4,
        electronAffinitykJMol: 295.1531,
        phaseAtSTP: 'solid',
        meltingPointK: 386.85,
        boilingPointK: 457.55,
        densityGcm3: 4.93,
    },
    Xe: {
        symbol: 'Xe',
        name: "Xenon",
        atomicNumber: 54,
        atomicWeight: 131.2936,
        period: 5,
        group: 18,
        category: "noble gas",
        electronConfiguration: "[Kr] 4d10 5s2 5p6",
        valenceElectrons: 8,
        commonOxidationStates: [0],
        electronegativity: 2.6,
        atomicRadiusPm: 216,
        ionizationEnergy1kJMol: 1170.4,
        electronAffinitykJMol: -77,
        phaseAtSTP: 'gas',
        meltingPointK: 161.36,
        boilingPointK: 165.03,
        densityGcm3: 0.005887,
    },
    Cs: {
        symbol: 'Cs',
        name: "Cesium",
        atomicNumber: 55,
        atomicWeight: 132.905451966,
        period: 6,
        group: 1,
        category: "alkali metal",
        electronConfiguration: "[Xe] 6s1",
        valenceElectrons: 1,
        commonOxidationStates: [1],
        electronegativity: 0.79,
        atomicRadiusPm: 343,
        ionizationEnergy1kJMol: 375.7,
        electronAffinitykJMol: 45.505,
        phaseAtSTP: 'solid',
        meltingPointK: 301.59,
        boilingPointK: 944,
        densityGcm3: 1.93,
    },
    Ba: {
        symbol: 'Ba',
        name: "Barium",
        atomicNumber: 56,
        atomicWeight: 137.3277,
        period: 6,
        group: 2,
        category: "alkaline earth metal",
        electronConfiguration: "[Xe] 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [2],
        electronegativity: 0.89,
        atomicRadiusPm: 268,
        ionizationEnergy1kJMol: 502.9,
        electronAffinitykJMol: 13.954,
        phaseAtSTP: 'solid',
        meltingPointK: 1000,
        boilingPointK: 2170,
        densityGcm3: 3.62,
    },
    La: {
        symbol: 'La',
        name: "Lanthanum",
        atomicNumber: 57,
        atomicWeight: 138.905477,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 5d16s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.1,
        atomicRadiusPm: 240,
        ionizationEnergy1kJMol: 538.1,
        electronAffinitykJMol: 53,
        phaseAtSTP: 'solid',
        meltingPointK: 1191,
        boilingPointK: 3737,
        densityGcm3: 6.15,
    },
    Ce: {
        symbol: 'Ce',
        name: "Cerium",
        atomicNumber: 58,
        atomicWeight: 140.1161,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f1 5d1 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [4, 3],
        electronegativity: 1.12,
        atomicRadiusPm: 235,
        ionizationEnergy1kJMol: 534.4,
        electronAffinitykJMol: 55,
        phaseAtSTP: 'solid',
        meltingPointK: 1071,
        boilingPointK: 3697,
        densityGcm3: 6.77,
    },
    Pr: {
        symbol: 'Pr',
        name: "Praseodymium",
        atomicNumber: 59,
        atomicWeight: 140.907662,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f3 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.13,
        atomicRadiusPm: 239,
        ionizationEnergy1kJMol: 527,
        electronAffinitykJMol: 93,
        phaseAtSTP: 'solid',
        meltingPointK: 1204,
        boilingPointK: 3793,
        densityGcm3: 6.77,
    },
    Nd: {
        symbol: 'Nd',
        name: "Neodymium",
        atomicNumber: 60,
        atomicWeight: 144.2423,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f4 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.14,
        atomicRadiusPm: 229,
        ionizationEnergy1kJMol: 533.1,
        electronAffinitykJMol: 184.87,
        phaseAtSTP: 'solid',
        meltingPointK: 1294,
        boilingPointK: 3347,
        densityGcm3: 7.01,
    },
    Pm: {
        symbol: 'Pm',
        name: "Promethium",
        atomicNumber: 61,
        atomicWeight: 145,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f5 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: null,
        atomicRadiusPm: 236,
        ionizationEnergy1kJMol: 540,
        electronAffinitykJMol: 12.45,
        phaseAtSTP: 'solid',
        meltingPointK: 1315,
        boilingPointK: 3273,
        densityGcm3: 7.26,
    },
    Sm: {
        symbol: 'Sm',
        name: "Samarium",
        atomicNumber: 62,
        atomicWeight: 150.362,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f6 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3, 2],
        electronegativity: 1.17,
        atomicRadiusPm: 229,
        ionizationEnergy1kJMol: 544.5,
        electronAffinitykJMol: 15.63,
        phaseAtSTP: 'solid',
        meltingPointK: 1347,
        boilingPointK: 2067,
        densityGcm3: 7.52,
    },
    Eu: {
        symbol: 'Eu',
        name: "Europium",
        atomicNumber: 63,
        atomicWeight: 151.9641,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f7 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3, 2],
        electronegativity: null,
        atomicRadiusPm: 233,
        ionizationEnergy1kJMol: 547.1,
        electronAffinitykJMol: 11.2,
        phaseAtSTP: 'solid',
        meltingPointK: 1095,
        boilingPointK: 1802,
        densityGcm3: 5.24,
    },
    Gd: {
        symbol: 'Gd',
        name: "Gadolinium",
        atomicNumber: 64,
        atomicWeight: 157.253,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f7 5d1 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.2,
        atomicRadiusPm: 237,
        ionizationEnergy1kJMol: 593.4,
        electronAffinitykJMol: 13.22,
        phaseAtSTP: 'solid',
        meltingPointK: 1586,
        boilingPointK: 3546,
        densityGcm3: 7.9,
    },
    Tb: {
        symbol: 'Tb',
        name: "Terbium",
        atomicNumber: 65,
        atomicWeight: 158.925352,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f9 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: null,
        atomicRadiusPm: 221,
        ionizationEnergy1kJMol: 565.8,
        electronAffinitykJMol: 112.4,
        phaseAtSTP: 'solid',
        meltingPointK: 1629,
        boilingPointK: 3503,
        densityGcm3: 8.23,
    },
    Dy: {
        symbol: 'Dy',
        name: "Dysprosium",
        atomicNumber: 66,
        atomicWeight: 162.5001,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f10 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.22,
        atomicRadiusPm: 229,
        ionizationEnergy1kJMol: 573,
        electronAffinitykJMol: 33.96,
        phaseAtSTP: 'solid',
        meltingPointK: 1685,
        boilingPointK: 2840,
        densityGcm3: 8.55,
    },
    Ho: {
        symbol: 'Ho',
        name: "Holmium",
        atomicNumber: 67,
        atomicWeight: 164.930332,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f11 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.23,
        atomicRadiusPm: 216,
        ionizationEnergy1kJMol: 581,
        electronAffinitykJMol: 32.61,
        phaseAtSTP: 'solid',
        meltingPointK: 1747,
        boilingPointK: 2973,
        densityGcm3: 8.8,
    },
    Er: {
        symbol: 'Er',
        name: "Erbium",
        atomicNumber: 68,
        atomicWeight: 167.2593,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f12 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.24,
        atomicRadiusPm: 235,
        ionizationEnergy1kJMol: 589.3,
        electronAffinitykJMol: 30.1,
        phaseAtSTP: 'solid',
        meltingPointK: 1802,
        boilingPointK: 3141,
        densityGcm3: 9.07,
    },
    Tm: {
        symbol: 'Tm',
        name: "Thulium",
        atomicNumber: 69,
        atomicWeight: 168.934222,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f13 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.25,
        atomicRadiusPm: 227,
        ionizationEnergy1kJMol: 596.7,
        electronAffinitykJMol: 99,
        phaseAtSTP: 'solid',
        meltingPointK: 1818,
        boilingPointK: 2223,
        densityGcm3: 9.32,
    },
    Yb: {
        symbol: 'Yb',
        name: "Ytterbium",
        atomicNumber: 70,
        atomicWeight: 173.0451,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f14 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3, 2],
        electronegativity: null,
        atomicRadiusPm: 242,
        ionizationEnergy1kJMol: 603.4,
        electronAffinitykJMol: -1.93,
        phaseAtSTP: 'solid',
        meltingPointK: 1092,
        boilingPointK: 1469,
        densityGcm3: 6.9,
    },
    Lu: {
        symbol: 'Lu',
        name: "Lutetium",
        atomicNumber: 71,
        atomicWeight: 174.96681,
        period: 6,
        group: 3,
        category: "lanthanide",
        electronConfiguration: "[Xe] 4f14 5d1 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.27,
        atomicRadiusPm: 221,
        ionizationEnergy1kJMol: 523.5,
        electronAffinitykJMol: 33.4,
        phaseAtSTP: 'solid',
        meltingPointK: 1936,
        boilingPointK: 3675,
        densityGcm3: 9.84,
    },
    Hf: {
        symbol: 'Hf',
        name: "Hafnium",
        atomicNumber: 72,
        atomicWeight: 178.492,
        period: 6,
        group: 4,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d2 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [4],
        electronegativity: 1.3,
        atomicRadiusPm: 212,
        ionizationEnergy1kJMol: 658.5,
        electronAffinitykJMol: 17.18,
        phaseAtSTP: 'solid',
        meltingPointK: 2506,
        boilingPointK: 4876,
        densityGcm3: 13.3,
    },
    Ta: {
        symbol: 'Ta',
        name: "Tantalum",
        atomicNumber: 73,
        atomicWeight: 180.947882,
        period: 6,
        group: 5,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d3 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [5],
        electronegativity: 1.5,
        atomicRadiusPm: 217,
        ionizationEnergy1kJMol: 761,
        electronAffinitykJMol: 31,
        phaseAtSTP: 'solid',
        meltingPointK: 3290,
        boilingPointK: 5731,
        densityGcm3: 16.4,
    },
    W: {
        symbol: 'W',
        name: "Tungsten",
        atomicNumber: 74,
        atomicWeight: 183.841,
        period: 6,
        group: 6,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d4 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [6],
        electronegativity: 2.36,
        atomicRadiusPm: 210,
        ionizationEnergy1kJMol: 770,
        electronAffinitykJMol: 78.76,
        phaseAtSTP: 'solid',
        meltingPointK: 3695,
        boilingPointK: 5828,
        densityGcm3: 19.3,
    },
    Re: {
        symbol: 'Re',
        name: "Rhenium",
        atomicNumber: 75,
        atomicWeight: 186.2071,
        period: 6,
        group: 7,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d5 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [7, 6, 4],
        electronegativity: 1.9,
        atomicRadiusPm: 217,
        ionizationEnergy1kJMol: 760,
        electronAffinitykJMol: 5.8273,
        phaseAtSTP: 'solid',
        meltingPointK: 3459,
        boilingPointK: 5869,
        densityGcm3: 20.8,
    },
    Os: {
        symbol: 'Os',
        name: "Osmium",
        atomicNumber: 76,
        atomicWeight: 190.233,
        period: 6,
        group: 8,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d6 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [4, 3],
        electronegativity: 2.2,
        atomicRadiusPm: 216,
        ionizationEnergy1kJMol: 840,
        electronAffinitykJMol: 103.99,
        phaseAtSTP: 'solid',
        meltingPointK: 3306,
        boilingPointK: 5285,
        densityGcm3: 22.57,
    },
    Ir: {
        symbol: 'Ir',
        name: "Iridium",
        atomicNumber: 77,
        atomicWeight: 192.2173,
        period: 6,
        group: 9,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d7 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [4, 3],
        electronegativity: 2.2,
        atomicRadiusPm: 202,
        ionizationEnergy1kJMol: 880,
        electronAffinitykJMol: 150.94,
        phaseAtSTP: 'solid',
        meltingPointK: 2719,
        boilingPointK: 4701,
        densityGcm3: 22.42,
    },
    Pt: {
        symbol: 'Pt',
        name: "Platinum",
        atomicNumber: 78,
        atomicWeight: 195.0849,
        period: 6,
        group: 10,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d9 6s1",
        valenceElectrons: 1,
        commonOxidationStates: [4, 2],
        electronegativity: 2.28,
        atomicRadiusPm: 209,
        ionizationEnergy1kJMol: 870,
        electronAffinitykJMol: 205.041,
        phaseAtSTP: 'solid',
        meltingPointK: 2041.55,
        boilingPointK: 4098,
        densityGcm3: 21.46,
    },
    Au: {
        symbol: 'Au',
        name: "Gold",
        atomicNumber: 79,
        atomicWeight: 196.9665695,
        period: 6,
        group: 11,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d10 6s1",
        valenceElectrons: 1,
        commonOxidationStates: [3, 1],
        electronegativity: 2.54,
        atomicRadiusPm: 166,
        ionizationEnergy1kJMol: 890.1,
        electronAffinitykJMol: 222.747,
        phaseAtSTP: 'solid',
        meltingPointK: 1337.33,
        boilingPointK: 3129,
        densityGcm3: 19.282,
    },
    Hg: {
        symbol: 'Hg',
        name: "Mercury",
        atomicNumber: 80,
        atomicWeight: 200.5923,
        period: 6,
        group: 12,
        category: "transition metal",
        electronConfiguration: "[Xe] 4f14 5d10 6s2",
        valenceElectrons: 2,
        commonOxidationStates: [2, 1],
        electronegativity: 2,
        atomicRadiusPm: 209,
        ionizationEnergy1kJMol: 1007.1,
        electronAffinitykJMol: -48,
        phaseAtSTP: 'liquid',
        meltingPointK: 234.32,
        boilingPointK: 629.88,
        densityGcm3: 13.5336,
    },
    Tl: {
        symbol: 'Tl',
        name: "Thallium",
        atomicNumber: 81,
        atomicWeight: 204.38,
        period: 6,
        group: 13,
        category: "post-transition metal",
        electronConfiguration: "[Xe] 4f14 5d10 6s2 6p1",
        valenceElectrons: 3,
        commonOxidationStates: [3, 1],
        electronegativity: 1.62,
        atomicRadiusPm: 196,
        ionizationEnergy1kJMol: 589.4,
        electronAffinitykJMol: 36.4,
        phaseAtSTP: 'solid',
        meltingPointK: 577,
        boilingPointK: 1746,
        densityGcm3: 11.8,
    },
    Pb: {
        symbol: 'Pb',
        name: "Lead",
        atomicNumber: 82,
        atomicWeight: 207.21,
        period: 6,
        group: 14,
        category: "post-transition metal",
        electronConfiguration: "[Xe] 4f14 5d10 6s2 6p2",
        valenceElectrons: 4,
        commonOxidationStates: [4, 2],
        electronegativity: 2.33,
        atomicRadiusPm: 202,
        ionizationEnergy1kJMol: 715.6,
        electronAffinitykJMol: 34.4204,
        phaseAtSTP: 'solid',
        meltingPointK: 600.61,
        boilingPointK: 2022,
        densityGcm3: 11.342,
    },
    Bi: {
        symbol: 'Bi',
        name: "Bismuth",
        atomicNumber: 83,
        atomicWeight: 208.980401,
        period: 6,
        group: 15,
        category: "post-transition metal",
        electronConfiguration: "[Xe] 4f14 5d10 6s2 6p3",
        valenceElectrons: 5,
        commonOxidationStates: [5, 3],
        electronegativity: 2.02,
        atomicRadiusPm: 207,
        ionizationEnergy1kJMol: 703,
        electronAffinitykJMol: 90.924,
        phaseAtSTP: 'solid',
        meltingPointK: 544.55,
        boilingPointK: 1837,
        densityGcm3: 9.807,
    },
    Po: {
        symbol: 'Po',
        name: "Polonium",
        atomicNumber: 84,
        atomicWeight: 209,
        period: 6,
        group: 16,
        category: "metalloid",
        electronConfiguration: "[Xe] 4f14 5d10 6s2 6p4",
        valenceElectrons: 6,
        commonOxidationStates: [4, 2],
        electronegativity: 2,
        atomicRadiusPm: 197,
        ionizationEnergy1kJMol: 812.1,
        electronAffinitykJMol: 136,
        phaseAtSTP: 'solid',
        meltingPointK: 527,
        boilingPointK: 1235,
        densityGcm3: 9.32,
    },
    At: {
        symbol: 'At',
        name: "Astatine",
        atomicNumber: 85,
        atomicWeight: 210,
        period: 6,
        group: 17,
        category: "halogen",
        electronConfiguration: "[Xe] 4f14 5d10 6s2 6p5",
        valenceElectrons: 7,
        commonOxidationStates: [7, 5, 3, 1, -1],
        electronegativity: 2.2,
        atomicRadiusPm: 202,
        ionizationEnergy1kJMol: 899.003,
        electronAffinitykJMol: 233,
        phaseAtSTP: 'solid',
        meltingPointK: 575,
        boilingPointK: null,
        densityGcm3: 7,
    },
    Rn: {
        symbol: 'Rn',
        name: "Radon",
        atomicNumber: 86,
        atomicWeight: 222,
        period: 6,
        group: 18,
        category: "noble gas",
        electronConfiguration: "[Xe] 4f14 5d10 6s2 6p6",
        valenceElectrons: 8,
        commonOxidationStates: [0],
        electronegativity: null,
        atomicRadiusPm: 220,
        ionizationEnergy1kJMol: 1037,
        electronAffinitykJMol: -68,
        phaseAtSTP: 'gas',
        meltingPointK: 202,
        boilingPointK: 211.45,
        densityGcm3: 0.00973,
    },
    Fr: {
        symbol: 'Fr',
        name: "Francium",
        atomicNumber: 87,
        atomicWeight: 223,
        period: 7,
        group: 1,
        category: "alkali metal",
        electronConfiguration: "[Rn] 7s1",
        valenceElectrons: 1,
        commonOxidationStates: [1],
        electronegativity: 0.7,
        atomicRadiusPm: 348,
        ionizationEnergy1kJMol: 380,
        electronAffinitykJMol: 46.89,
        phaseAtSTP: 'solid',
        meltingPointK: 300,
        boilingPointK: null,
        densityGcm3: null,
    },
    Ra: {
        symbol: 'Ra',
        name: "Radium",
        atomicNumber: 88,
        atomicWeight: 226,
        period: 7,
        group: 2,
        category: "alkaline earth metal",
        electronConfiguration: "[Rn] 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [2],
        electronegativity: 0.9,
        atomicRadiusPm: 283,
        ionizationEnergy1kJMol: 509.3,
        electronAffinitykJMol: 9.6485,
        phaseAtSTP: 'solid',
        meltingPointK: 973,
        boilingPointK: 1413,
        densityGcm3: 5,
    },
    Ac: {
        symbol: 'Ac',
        name: "Actinium",
        atomicNumber: 89,
        atomicWeight: 227,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 6d1 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.1,
        atomicRadiusPm: 260,
        ionizationEnergy1kJMol: 499,
        electronAffinitykJMol: 33.77,
        phaseAtSTP: 'solid',
        meltingPointK: 1324,
        boilingPointK: 3471,
        densityGcm3: 10.07,
    },
    Th: {
        symbol: 'Th',
        name: "Thorium",
        atomicNumber: 90,
        atomicWeight: 232.03774,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 6d2 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [4],
        electronegativity: 1.3,
        atomicRadiusPm: 237,
        ionizationEnergy1kJMol: 587,
        electronAffinitykJMol: 112.72,
        phaseAtSTP: 'solid',
        meltingPointK: 2023,
        boilingPointK: 5061,
        densityGcm3: 11.72,
    },
    Pa: {
        symbol: 'Pa',
        name: "Protactinium",
        atomicNumber: 91,
        atomicWeight: 231.035882,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f2 6d1 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [5, 4],
        electronegativity: 1.5,
        atomicRadiusPm: 243,
        ionizationEnergy1kJMol: 568,
        electronAffinitykJMol: 53.03,
        phaseAtSTP: 'solid',
        meltingPointK: 1845,
        boilingPointK: null,
        densityGcm3: 15.37,
    },
    U: {
        symbol: 'U',
        name: "Uranium",
        atomicNumber: 92,
        atomicWeight: 238.028913,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f3 6d1 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [6, 5, 4, 3],
        electronegativity: 1.38,
        atomicRadiusPm: 240,
        ionizationEnergy1kJMol: 597.6,
        electronAffinitykJMol: 50.94,
        phaseAtSTP: 'solid',
        meltingPointK: 1408,
        boilingPointK: 4404,
        densityGcm3: 18.95,
    },
    Np: {
        symbol: 'Np',
        name: "Neptunium",
        atomicNumber: 93,
        atomicWeight: 237,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f4 6d1 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [6, 5, 4, 3],
        electronegativity: 1.36,
        atomicRadiusPm: 221,
        ionizationEnergy1kJMol: 604.5,
        electronAffinitykJMol: 45.85,
        phaseAtSTP: 'solid',
        meltingPointK: 917,
        boilingPointK: 4175,
        densityGcm3: 20.25,
    },
    Pu: {
        symbol: 'Pu',
        name: "Plutonium",
        atomicNumber: 94,
        atomicWeight: 244,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f6 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [6, 5, 4, 3],
        electronegativity: 1.28,
        atomicRadiusPm: 243,
        ionizationEnergy1kJMol: 584.7,
        electronAffinitykJMol: -48.33,
        phaseAtSTP: 'solid',
        meltingPointK: 913,
        boilingPointK: 3501,
        densityGcm3: 19.84,
    },
    Am: {
        symbol: 'Am',
        name: "Americium",
        atomicNumber: 95,
        atomicWeight: 243,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f7 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [6, 5, 4, 3],
        electronegativity: 1.3,
        atomicRadiusPm: 244,
        ionizationEnergy1kJMol: 578,
        electronAffinitykJMol: 9.93,
        phaseAtSTP: 'solid',
        meltingPointK: 1449,
        boilingPointK: 2284,
        densityGcm3: 13.69,
    },
    Cm: {
        symbol: 'Cm',
        name: "Curium",
        atomicNumber: 96,
        atomicWeight: 247,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f7 6d1 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.3,
        atomicRadiusPm: 245,
        ionizationEnergy1kJMol: 581,
        electronAffinitykJMol: 27.17,
        phaseAtSTP: 'solid',
        meltingPointK: 1618,
        boilingPointK: 3400,
        densityGcm3: 13.51,
    },
    Bk: {
        symbol: 'Bk',
        name: "Berkelium",
        atomicNumber: 97,
        atomicWeight: 247,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f9 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [4, 3],
        electronegativity: 1.3,
        atomicRadiusPm: 244,
        ionizationEnergy1kJMol: 601,
        electronAffinitykJMol: -165.24,
        phaseAtSTP: 'solid',
        meltingPointK: 1323,
        boilingPointK: null,
        densityGcm3: 14,
    },
    Cf: {
        symbol: 'Cf',
        name: "Californium",
        atomicNumber: 98,
        atomicWeight: 251,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f10 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.3,
        atomicRadiusPm: 245,
        ionizationEnergy1kJMol: 608,
        electronAffinitykJMol: -97.31,
        phaseAtSTP: 'solid',
        meltingPointK: 1173,
        boilingPointK: null,
        densityGcm3: null,
    },
    Es: {
        symbol: 'Es',
        name: "Einsteinium",
        atomicNumber: 99,
        atomicWeight: 252,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f11 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.3,
        atomicRadiusPm: 245,
        ionizationEnergy1kJMol: 619,
        electronAffinitykJMol: -28.6,
        phaseAtSTP: 'solid',
        meltingPointK: 1133,
        boilingPointK: null,
        densityGcm3: null,
    },
    Fm: {
        symbol: 'Fm',
        name: "Fermium",
        atomicNumber: 100,
        atomicWeight: 257,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f12 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [3],
        electronegativity: 1.3,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: 627,
        electronAffinitykJMol: 33.96,
        phaseAtSTP: 'solid',
        meltingPointK: 1800,
        boilingPointK: null,
        densityGcm3: null,
    },
    Md: {
        symbol: 'Md',
        name: "Mendelevium",
        atomicNumber: 101,
        atomicWeight: 258,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f13 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [3, 2],
        electronegativity: 1.3,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: 635,
        electronAffinitykJMol: 93.91,
        phaseAtSTP: 'solid',
        meltingPointK: 1100,
        boilingPointK: null,
        densityGcm3: null,
    },
    No: {
        symbol: 'No',
        name: "Nobelium",
        atomicNumber: 102,
        atomicWeight: 259,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f14 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [3, 2],
        electronegativity: 1.3,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: 642,
        electronAffinitykJMol: -223.22,
        phaseAtSTP: 'solid',
        meltingPointK: 1100,
        boilingPointK: null,
        densityGcm3: null,
    },
    Lr: {
        symbol: 'Lr',
        name: "Lawrencium",
        atomicNumber: 103,
        atomicWeight: 266,
        period: 7,
        group: 3,
        category: "actinide",
        electronConfiguration: "[Rn] 5f14 7s2 7p1",
        valenceElectrons: 3,
        commonOxidationStates: [3],
        electronegativity: 1.3,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: 470,
        electronAffinitykJMol: -30.04,
        phaseAtSTP: 'solid',
        meltingPointK: 1900,
        boilingPointK: null,
        densityGcm3: null,
    },
    Rf: {
        symbol: 'Rf',
        name: "Rutherfordium",
        atomicNumber: 104,
        atomicWeight: 267,
        period: 7,
        group: 4,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d2 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [4],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: 580,
        electronAffinitykJMol: null,
        phaseAtSTP: 'solid',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Db: {
        symbol: 'Db',
        name: "Dubnium",
        atomicNumber: 105,
        atomicWeight: 268,
        period: 7,
        group: 5,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d3 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [5, 4, 3],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: null,
        phaseAtSTP: 'solid',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Sg: {
        symbol: 'Sg',
        name: "Seaborgium",
        atomicNumber: 106,
        atomicWeight: 269,
        period: 7,
        group: 6,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d4 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [6, 5, 4, 3, 0],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: null,
        phaseAtSTP: 'solid',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Bh: {
        symbol: 'Bh',
        name: "Bohrium",
        atomicNumber: 107,
        atomicWeight: 270,
        period: 7,
        group: 7,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d5 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [7, 5, 4, 3],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: null,
        phaseAtSTP: 'solid',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Hs: {
        symbol: 'Hs',
        name: "Hassium",
        atomicNumber: 108,
        atomicWeight: 269,
        period: 7,
        group: 8,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d6 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [8, 6, 5, 4, 3, 2],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: null,
        phaseAtSTP: 'solid',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Mt: {
        symbol: 'Mt',
        name: "Meitnerium",
        atomicNumber: 109,
        atomicWeight: 278,
        period: 7,
        group: 9,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d7 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [9, 8, 6, 4, 3, 1],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: null,
        phaseAtSTP: 'solid',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Ds: {
        symbol: 'Ds',
        name: "Darmstadtium",
        atomicNumber: 110,
        atomicWeight: 281,
        period: 7,
        group: 10,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d9 7s1",
        valenceElectrons: 2,
        commonOxidationStates: [8, 6, 4, 2, 0],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: null,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Rg: {
        symbol: 'Rg',
        name: "Roentgenium",
        atomicNumber: 111,
        atomicWeight: 282,
        period: 7,
        group: 11,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d10 7s1",
        valenceElectrons: 2,
        commonOxidationStates: [5, 3, 1, -1],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: 151,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Cn: {
        symbol: 'Cn',
        name: "Copernicium",
        atomicNumber: 112,
        atomicWeight: 285,
        period: 7,
        group: 12,
        category: "transition metal",
        electronConfiguration: "[Rn] 5f14 6d10 7s2",
        valenceElectrons: 2,
        commonOxidationStates: [2, 1, 0],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: null,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Nh: {
        symbol: 'Nh',
        name: "Nihonium",
        atomicNumber: 113,
        atomicWeight: 286,
        period: 7,
        group: 13,
        category: "post-transition metal",
        electronConfiguration: "[Rn] 5f14 6d10 7s2 7p1",
        valenceElectrons: 3,
        commonOxidationStates: [],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: 66.6,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Fl: {
        symbol: 'Fl',
        name: "Flerovium",
        atomicNumber: 114,
        atomicWeight: 289,
        period: 7,
        group: 14,
        category: "post-transition metal",
        electronConfiguration: "[Rn] 5f14 6d10 7s2 7p2",
        valenceElectrons: 4,
        commonOxidationStates: [6, 4, 2, 1, 0],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: null,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Mc: {
        symbol: 'Mc',
        name: "Moscovium",
        atomicNumber: 115,
        atomicWeight: 289,
        period: 7,
        group: 15,
        category: "post-transition metal",
        electronConfiguration: "[Rn] 5f14 6d10 7s2 7p3",
        valenceElectrons: 5,
        commonOxidationStates: [3, 1],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: 35.3,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Lv: {
        symbol: 'Lv',
        name: "Livermorium",
        atomicNumber: 116,
        atomicWeight: 293,
        period: 7,
        group: 16,
        category: "post-transition metal",
        electronConfiguration: "[Rn] 5f14 6d10 7s2 7p4",
        valenceElectrons: 6,
        commonOxidationStates: [4, 2, -2],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: 74.9,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Ts: {
        symbol: 'Ts',
        name: "Tennessine",
        atomicNumber: 117,
        atomicWeight: 294,
        period: 7,
        group: 17,
        category: "halogen",
        electronConfiguration: "[Rn] 5f14 6d10 7s2 7p5",
        valenceElectrons: 7,
        commonOxidationStates: [5, 3, 1, -1],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: 165.9,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
    Og: {
        symbol: 'Og',
        name: "Oganesson",
        atomicNumber: 118,
        atomicWeight: 294,
        period: 7,
        group: 18,
        category: "noble gas",
        electronConfiguration: "[Rn] 5f14 6d10 7s2 7p6",
        valenceElectrons: 8,
        commonOxidationStates: [6, 4, 2, 1, 0, -1],
        electronegativity: null,
        atomicRadiusPm: null,
        ionizationEnergy1kJMol: null,
        electronAffinitykJMol: 5.40318,
        phaseAtSTP: 'unknown',
        meltingPointK: null,
        boilingPointK: null,
        densityGcm3: null,
    },
};

export const ElementSymbols = Array.from(Object.keys(PeriodicTable));